[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.frontend"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
numReplicas = 2

[deploy.env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
