[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run db:deploy && npm run start:prod"
healthcheckPath = "/health/liveness"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
PORT = "8080"
